<a href="https://colab.research.google.com/github/sakeththelu/NLP/blob/main/4082_nlp_12_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 23.3 MB/s eta 0:00:00


In [39]:
# Numerical operations
import numpy as np

# Keras modules
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, Conv1D
from tensorflow.keras.layers import GlobalMaxPooling1D, Dense, Concatenate
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Gensim for Word2Vec
from gensim.models import Word2Vec

In [40]:
texts = [
    "this movie is great",
    "i love this film",
    "this movie is terrible",
    "i hate this film",
    "excellent acting",
    "poor story"
]

# Labels: 1 = positive, 0 = negative
labels = [1,1,0,0,1,0]


In [41]:
tokenizer = Tokenizer()

# Learn vocabulary
tokenizer.fit_on_texts(texts)

# Convert sentences into sequences
sequences = tokenizer.texts_to_sequences(texts)

# Vocabulary dictionary
word_index = tokenizer.word_index

print(word_index)

{'this': 1, 'movie': 2, 'is': 3, 'i': 4, 'film': 5, 'great': 6, 'love': 7, 'terrible': 8, 'hate': 9, 'excellent': 10, 'acting': 11, 'poor': 12, 'story': 13}


In [42]:
print(sequences)

[[1, 2, 3, 6], [4, 7, 1, 5], [1, 2, 3, 8], [4, 9, 1, 5], [10, 11], [12, 13]]


In [48]:
max_length = 6

X = pad_sequences(sequences, maxlen=max_length)

y = np.array(labels)

In [49]:
X

array([[ 0,  0,  1,  2,  3,  6],
       [ 0,  0,  4,  7,  1,  5],
       [ 0,  0,  1,  2,  3,  8],
       [ 0,  0,  4,  9,  1,  5],
       [ 0,  0,  0,  0, 10, 11],
       [ 0,  0,  0,  0, 12, 13]], dtype=int32)

In [50]:
sentences = [text.split() for text in texts]

# Train Word2Vec
w2v_model = Word2Vec(
    sentences,
    vector_size=50,
    window=3,
    min_count=1
)

In [51]:
embedding_matrix[1]

tensor([ 0.5912,  0.0357,  0.2695, -0.5840, -0.2517,  0.4903, -0.5591,  0.0101,
        -1.1056, -0.9628,  1.5783,  0.7625,  0.4170,  0.6466,  0.6379,  0.3344,
         0.1450, -0.0058, -0.3861,  0.1921, -0.2616, -0.0173, -0.3030, -0.6313,
         0.2619, -0.6661,  0.6026,  0.2504, -0.8575,  0.5167, -0.7945,  0.2135,
         0.5877,  0.2693,  0.8269, -0.1098,  0.2776, -0.0763,  0.5426,  0.4376,
        -0.1357,  0.0999,  0.1237,  0.5885, -0.4486, -0.4442,  0.0305, -1.2874,
        -0.0545, -0.3031, -0.4683,  1.3444,  0.4040, -0.4278,  0.7566,  0.7102,
         0.4190,  0.9406,  0.0942,  0.2535, -0.6880,  0.1077,  0.2698,  0.4191,
         0.3891,  0.2000, -0.3184,  0.1516,  1.2265,  0.3428,  0.2034, -0.6570,
        -0.3497,  0.1980, -0.6647, -0.1986, -0.1251, -0.3299, -1.0232, -0.1845,
         0.6783,  0.4614, -0.1746,  0.6481,  0.6648,  0.2076, -0.0424, -0.0460,
         1.2701, -0.6094, -0.2957,  1.6960, -0.3508, -0.4854,  0.1910, -0.0329,
        -0.2840, -0.0232, -0.7335,  0.48

In [52]:
embedding_matrix[1]

tensor([ 0.5912,  0.0357,  0.2695, -0.5840, -0.2517,  0.4903, -0.5591,  0.0101,
        -1.1056, -0.9628,  1.5783,  0.7625,  0.4170,  0.6466,  0.6379,  0.3344,
         0.1450, -0.0058, -0.3861,  0.1921, -0.2616, -0.0173, -0.3030, -0.6313,
         0.2619, -0.6661,  0.6026,  0.2504, -0.8575,  0.5167, -0.7945,  0.2135,
         0.5877,  0.2693,  0.8269, -0.1098,  0.2776, -0.0763,  0.5426,  0.4376,
        -0.1357,  0.0999,  0.1237,  0.5885, -0.4486, -0.4442,  0.0305, -1.2874,
        -0.0545, -0.3031, -0.4683,  1.3444,  0.4040, -0.4278,  0.7566,  0.7102,
         0.4190,  0.9406,  0.0942,  0.2535, -0.6880,  0.1077,  0.2698,  0.4191,
         0.3891,  0.2000, -0.3184,  0.1516,  1.2265,  0.3428,  0.2034, -0.6570,
        -0.3497,  0.1980, -0.6647, -0.1986, -0.1251, -0.3299, -1.0232, -0.1845,
         0.6783,  0.4614, -0.1746,  0.6481,  0.6648,  0.2076, -0.0424, -0.0460,
         1.2701, -0.6094, -0.2957,  1.6960, -0.3508, -0.4854,  0.1910, -0.0329,
        -0.2840, -0.0232, -0.7335,  0.48

In [53]:
input_layer = Input(shape=(max_length,))

In [54]:
embedding_layer = Embedding(
    input_dim=vocab_size,
    output_dim=embedding_dim,
    weights=[embedding_matrix],  # Word2Vec weights
    input_length=max_length,
    trainable=False               # keep embeddings fixed
)(input_layer)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [55]:

conv1 = Conv1D(filters=100, kernel_size=3, activation='relu')(embedding_layer)

conv2 = Conv1D(filters=100, kernel_size=4, activation='relu')(embedding_layer)

conv3 = Conv1D(filters=100, kernel_size=5, activation='relu')(embedding_layer)

In [56]:
pool1 = GlobalMaxPooling1D()(conv1)
pool2 = GlobalMaxPooling1D()(conv2)
pool3 = GlobalMaxPooling1D()(conv3)

In [57]:
merged = Concatenate()([pool1, pool2, pool3])

In [58]:
dense = Dense(10, activation='relu')(merged)

In [59]:
output = Dense(1, activation='sigmoid')(dense)

In [60]:
model = Model(inputs=input_layer, outputs=output)

In [61]:

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [62]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 6)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding           │ (None, 6, 100)    │    966,300 │ input_layer[0][0] │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d (Conv1D)     │ (None, 4, 100)    │     30,100 │ embedding[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_1 (Conv1D)   │ (None, 3, 100)    │     40,100 │ embedding[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_2 (Conv1D)   │ (None, 2, 100)    │     50,100 │ embedding[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_max_pooling… │ (None, 100)       │          0 │ conv1d[0][0]      │
│ (GlobalMaxPooling1… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_max_pooling… │ (None, 100)       │          0 │ conv1d_1[0][0]    │
│ (GlobalMaxPooling1… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_max_pooling… │ (None, 100)       │          0 │ conv1d_2[0][0]    │
│ (GlobalMaxPooling1… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 300)       │          0 │ global_max_pooli… │
│ (Concatenate)       │                   │            │ global_max_pooli… │
│                     │                   │            │ global_max_pooli… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 10)        │      3,010 │ concatenate[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 1)         │         11 │ dense[0][0]       │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 1,089,621 (4.16 MB)

 Trainable params: 123,321 (481.72 KB)

 Non-trainable params: 966,300 (3.69 MB)

In [63]:
model.fit(
    X,
    y,
    epochs=10,
    batch_size=2
)


Epoch 1/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.1667 - loss: 0.7468  
Epoch 2/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6667 - loss: 0.6402
Epoch 3/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8333 - loss: 0.5832
Epoch 4/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8333 - loss: 0.5305
Epoch 5/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8333 - loss: 0.5094
Epoch 6/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8333 - loss: 0.4773
Epoch 7/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8333 - loss: 0.4536
Epoch 8/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8333 - loss: 0.4336
Epoch 9/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6667 - loss: 0.4294
Epoch 10/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8333 - loss: 0.4042


In [64]:
test_text = ["this movie is amazing"]

seq = tokenizer.texts_to_sequences(test_text)

pad = pad_sequences(seq, maxlen=max_length)

prediction = model.predict(pad)

print(prediction)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step
[[0.6037521]]
